using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RoA.Memory
{
    public enum eMolloSkins
    {
        DEFAULT,
        BLUE,
        WHITE_RED,
        GREEN_YELLOW,
        GRAY,
        TRANS,
        CALENDAR,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        UNKNOWN11,
        UNKNOWN12,
        ABYSS,
        EARLY_ACCESS,
        UNKNOWN15,
        UNKNOWN16,
        UNKNOWN17,
        RANKED_GOLD,
        UNKNOWN19,
        UNKNOWN20
    }

    public enum eClairenSkins
    {
        DEFAULT,
        BLUE,
        ORANGE,
        GREEN,
        PURPLE,
        WHITE,
        CALENDAR,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        GENESIS,
        LINK,
        ABYSS,
        EARLY_ACCESS,
        UNKNOWN15,
        INFAMOUS,        
        UNKNOWN17,
        RANKED_GOLD,
        UNKNOWN19,
        UNKNOWN20
    }

    public enum eForsburnSkins
    {
        DEFAULT,
        BLUE,
        RED,
        GREEN,
        WHITE,
        PURPLE,
        CALENDAR,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        GENESIS,
        UNKNOWN12,
        ABYSS,
        EARLY_ACCESS,
        UNKNOWN15,
        UNKNOWN16,
        UNKNOWN17,
        RANKED_GOLD,
        UNKNOWN19,
        UNKNOWN20
    }
    
    public enum eZetterburnSkins
    {
        DEFAULT,
        BLUE,
        RED,
        GREEN,
        BLACK_WHITE,
        PURPLE_WHITE,
        CALENDAR,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        CHAMPION,
        EXCALIBUR,
        ABYSS,
        EARLY_ACCESS,
        SHINE,        
        UNKNOWN16,
        UNKNOWN17,
        RANKED_GOLD,
        UNKNOWN19,
        UNKNOWN20
    }

    public enum eWrastorSkins
    {
        DEFAULT,
        BLUE,
        RED,
        GREEN,
        BLACK,
        PURPLE_BROWN,
        CALENDAR,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        AMERICA,
        UNKNOWN12,
        ABYSS,
        EARLY_ACCESS,
        UNKNOWN15,
        UNKNOWN16,
        UNKNOWN17,
        RANKED_GOLD,
        UNKNOWN19,
        UNKNOWN20
    }

    public enum eAbsaSkins
    {
        DEFAULT,
        BLUE_HAIR,
        BROWN_PINK_HAIR,
        GREEN,
        BLACK_WHITE_GRAY,
        PURPLE_YELLOW_HAIR,
        CALENDAR,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        TWITCH,
        UNKNOWN12,
        ABYSS,
        EARLY_ACCESS,
        PENGUIN,
        UNKNOWN16,
        UNKNOWN17,
        RANKED_GOLD,
        UNKNOWN19,
        UNKNOWN20
    }

    public enum eEllianaSkins
    {
        DEFAULT,
        BLUE,
        RED,
        GREEN,
        BLACK,
        PURPLE,
        CALENDAR,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        UNKNOWN11,
        UNKNOWN12,
        ABYSS,
        EARLY_ACCESS,
        INFAMOUS,
        UNKNOWN16,
        UNKNOWN17,
        RANKED_GOLD,
        UNKNOWN19,
        UNKNOWN20
    }

    public enum ePommeSkins
    {
        DEFAULT,
        DARKBLUE_JACKET,
        RED_JACKET,
        GREEN_JACKET,
        BLACK_WHITE,
        PURPLE,
        CALENDAR,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        UNKNOWN11,
        UNKNOWN12,
        ABYSS,
        EARLY_ACCESS,
        UNKNOWN15,
        UNKNOWN16,
        UNKNOWN17,
        RANKED_GOLD,
        UNKNOWN19,
        UNKNOWN20
    }

    public enum eOlympiaSkins
    {
        DEFAULT,
        BLUE,
        RED_YELLOW,
        GREEN,
        BLACK_SILVER,
        PURPLE_RUBY,
        CALENDAR,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        UNKNOWN11,
        UNKNOWN12,
        ABYSS,
        EARLY_ACCESS,
        UNKNOWN15,
        UNKNOWN16,
        UNKNOWN17,
        RANKED_GOLD,
        UNKNOWN19,
        UNKNOWN20
    }

    public enum eSylvanosSkins
    {
        DEFAULT,
        BLUE,
        ORANGE,
        LIGHT_GREEN,
        WHITE,
        PURPLE,
        CALENDAR,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        GENESIS,
        INFAMOUS,
        ABYSS,
        EARLY_ACCESS,
        UNKNOWN15,
        UNKNOWN16,
        UNKNOWN17,
        RANKED_GOLD,
        UNKNOWN19,
        UNKNOWN20
    }

    public enum eMaypulSkins
    {
        DEFAULT,
        BLUE,
        RED,
        YELLOW,
        BLACK,
        PURPLE,
        CALENDAR,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        PANDA,
        ARCADE,
        ABYSS,
        EARLY_ACCESS,
        UNKNOWN15,
        UNKNOWN16,
        UNKNOWN17,
        RANKED_GOLD,
        UNKNOWN19,
        UNKNOWN20
    }

    public enum eKraggSkins
    {
        DEFAULT,
        BLUE,
        PINK,
        GREEN,
        BLACK_GRAY,
        PURPLE,
        CALENDAR,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        SUMMIT,
        CHAMPION,
        ABYSS,
        EARLY_ACCESS,
        BURRITO,
        UNKNOWN16,
        UNKNOWN17,
        RANKED_GOLD,
        GENESIS,
        UNKNOWN20
    }

    public enum eOriSkins
    {
        DEFAULT,
        BLUE,
        RED,
        GREEN,
        BLACK,
        PINK,
        CALENDAR,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        INFAMOUS,
        UNKNOWN12,
        ABYSS,
        EARLY_ACCESS,
        UNKNOWN15,
        UNKNOWN16,
        UNKNOWN17,
        RANKED_GOLD,
        UNKNOWN19,
        UNKNOWN20
    }

    public enum eShovelKnightSkins
    {
        DEFAULT,
        LIGHT_BLUE,
        RED_ORANGE,
        GREEN,
        BLACK_RED,
        PURPLE,
        CALENDAR,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        UNKNOWN11,
        INFAMOUS,
        ABYSS,
        EARLY_ACCESS,
        UNKNOWN15,
        UNKNOWN16,
        UNKNOWN17,
        RANKED_GOLD,
        UNKNOWN19,
        UNKNOWN20
    }

    public enum eOrcaneSkins
    {
        DEFAULT,
        LIGHT_BLUE,
        RED,
        GREEN,
        BLACK,
        PURPLE_YELLOW,
        CALENDAR,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        GOLD,
        SUMMIT,
        ABYSS,
        EARLY_ACCESS,
        UNKNOWN15,
        UNKNOWN16,
        STEAMPUNK,
        RANKED_GOLD,
        UNKNOWN19,
        UNKNOWN20
    }

    public enum eEtalusSkins
    {
        DEFAULT,
        BLUE,
        YELLOW,
        GREEN,
        BLACK,
        PINK,
        CALENDAR,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        CHAMPION,
        UNKNOWN12,
        ABYSS,
        EARLY_ACCESS,
        UNKNOWN15,
        GENESIS,
        UNKNOWN17,
        RANKED_GOLD,
        UNKNOWN19,
        UNKNOWN20
    }

    public enum eRannoSkins
    {
        DEFAULT,
        PURPLE,
        RED,
        GREEN,
        GRAY,
        PINK_WHITE_SMOKE,
        CALENDAR,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        UNKNOWN11,
        UNKNOWN12,
        ABYSS,
        EARLY_ACCESS,
        UNKNOWN15,
        UNKNOWN16,
        INFAMOUS,
        RANKED_GOLD,
        UNKNOWN19,
        UNKNOWN20
    }

    public enum eHodanSkins
    {
        DEFAULT,
        BLUE,
        RED,
        GREEN,
        BLACK,
        PINK,
        CALENDAR,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        UNKNOWN11,
        UNKNOWN12,
        ABYSS,
        EARLY_ACCESS,
        UNKNOWN15,
        UNKNOWN16,
        UNKNOWN17,
        RANKED_GOLD,
        UNKNOWN19,
        UNKNOWN20
    }
}
