using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RoA.Memory
{
    public enum eMolloSkins
    {
        DEFAULT,
        BLUE,
        RED,
        GREEN,
        GREY,
        PURPLE,
        SEASONAL,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        UNKNOWN11,
        UNKNOWN12,
        ABYSS,
        EARLY_ACCESS,
        UNKNOWN15,
        UNKNOWN16,
        UNKNOWN17,
        RANKED,
        UNKNOWN19,
        UNKNOWN20
    }

    public enum eClairenSkins
    {
        DEFAULT,
        BLUE,
        RED,
        GREEN,
        GREY,
        PURPLE,
        SEASONAL,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        OUTLINE,
        GENESIS,
        LINK,
        ABYSS,
        EARLY_ACCESS,
        ARCADE,
        INFAMOUS,        
        CHAMPION,
        RANKED,
        GOLDEN_PLUSH,
        HEAT_WAVE
    }

    public enum eForsburnSkins
    {
        DEFAULT,
        BLUE,
        RED,
        GREEN,
        GREY,
        PURPLE,
        SEASONAL,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        GENESIS,
        HEAT_WAVE,
        ABYSS,
        EARLY_ACCESS,
        CHAMPION,
        DREAMSCAPE,
        LOA,
        RANKED,
        GOLDEN_PLUSH,
        UNKNOWN20
    }
    
    public enum eZetterburnSkins
    {
        DEFAULT,
        BLUE,
        RED,
        GREEN,
        GREY,
        PURPLE,
        SEASONAL,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        CHAMPION,
        EXCALIBUR,
        ABYSS,
        EARLY_ACCESS,
        SHINE,        
        GOLDEN_PLUSH,
        LOA,
        RANKED,
        STEAMPUNK,
        UNKNOWN20
    }

    public enum eWrastorSkins
    {
        DEFAULT,
        BLUE,
        RED,
        GREEN,
        GREY,
        PURPLE,
        SEASONAL,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        AMERICA,
        CHAMPION,
        ABYSS,
        EARLY_ACCESS,
        BRADSHAW,
        COLLEGIATE,
        GOLDEN_PLUSH,
        RANKED,
        WHITE_GOLD,
        UNKNOWN20
    }

    public enum eAbsaSkins
    {
        DEFAULT,
        BLUE,
        RED,
        GREEN,
        GREY,
        PURPLE,
        SEASONAL,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        TWITCH,
        CHAMPION,
        ABYSS,
        EARLY_ACCESS,
        PENGUIN,
        LOA,
        GOLDEN_PLUSH,
        RANKED,
        STEAMPUNK,
        HIGH_ROLLER
    }

    public enum eEllianaSkins
    {
        DEFAULT,
        BLUE,
        RED,
        GREEN,
        GREY,
        PURPLE,
        SEASONAL,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        ARCADE,
        AYALA,
        ABYSS,
        EARLY_ACCESS,
        INFAMOUS,
        ON_THE_EDGE,
        CHAMPION,
        RANKED,
        GOLDEN_PLUSH,
        UNKNOWN20
    }

    public enum ePommeSkins
    {
        DEFAULT,
        BLUE,
        RED,
        GREEN,
        GREY,
        PURPLE,
        SEASONAL,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        UNKNOWN11,
        UNKNOWN12,
        ABYSS,
        EARLY_ACCESS,
        UNKNOWN15,
        UNKNOWN16,
        UNKNOWN17,
        RANKED,
        UNKNOWN19,
        UNKNOWN20
    }

    public enum eOlympiaSkins
    {
        DEFAULT,
        BLUE,
        RED,
        GREEN,
        GREY,
        PURPLE,
        SEASONAL,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        UNKNOWN11,
        UNKNOWN12,
        ABYSS,
        EARLY_ACCESS,
        UNKNOWN15,
        UNKNOWN16,
        UNKNOWN17,
        RANKED,
        UNKNOWN19,
        UNKNOWN20
    }

    public enum eSylvanosSkins
    {
        DEFAULT,
        BLUE,
        RED,
        GREEN,
        GREY,
        PURPLE,
        SEASONAL,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        GENESIS,
        INFAMOUS,
        ABYSS,
        EARLY_ACCESS,
        GOLDEN_PLUSH,
        CHAMPION,
        UNKNOWN17,
        RANKED,
        STEAMPUNK,
        UNKNOWN20
    }

    public enum eMaypulSkins
    {
        DEFAULT,
        BLUE,
        RED,
        GREEN,
        GREY,
        PURPLE,
        SEASONAL,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        PANDA,
        ARCADE,
        ABYSS,
        EARLY_ACCESS,
        RAGNIR,
        GOLDEN_PLUSH,
        CHAMPION,
        RANKED,
        ON_THE_EDGE,
        UNKNOWN20
    }

    public enum eKraggSkins
    {
        DEFAULT,
        BLUE,
        RED,
        GREEN,
        GREY,
        PURPLE,
        SEASONAL,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        SUMMIT,
        CHAMPION,
        ABYSS,
        EARLY_ACCESS,
        BURRITO,
        GOLDEN_PLUSH,
        UNKNOWN17,
        RANKED,
        GENESIS,
        UNKNOWN20
    }

    public enum eOriSkins
    {
        DEFAULT,
        BLUE,
        RED,
        GREEN,
        GREY,
        PURPLE,
        SEASONAL,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        INFAMOUS,
        CHAMPION,
        ABYSS,
        EARLY_ACCESS,
        UNKNOWN15,
        UNKNOWN16,
        UNKNOWN17,
        RANKED,
        UNKNOWN19,
        UNKNOWN20
    }

    public enum eShovelKnightSkins
    {
        DEFAULT,
        BLUE,
        RED,
        GREEN,
        GREY,
        PURPLE,
        SEASONAL,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        GOLDEN_PLUSH,
        INFAMOUS,
        ABYSS,
        EARLY_ACCESS,
        CHAMPION,
        UNKNOWN16,
        UNKNOWN17,
        RANKED,
        HEAT_WAVE,
        UNKNOWN20
    }

    public enum eOrcaneSkins
    {
        DEFAULT,
        BLUE,
        RED,
        GREEN,
        GREY,
        PURPLE,
        SEASONAL,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        GOLDEN_PLUSH,
        SUMMIT,
        ABYSS,
        EARLY_ACCESS,
        POOL_PARTY,
        CHAMPION,
        STEAMPUNK,
        RANKED,
        UNKNOWN19,
        UNKNOWN20
    }

    public enum eEtalusSkins
    {
        DEFAULT,
        BLUE,
        RED,
        GREEN,
        GREY,
        PURPLE,
        SEASONAL,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        CHAMPION,
        GOLDEN_PLUSH,
        ABYSS,
        EARLY_ACCESS,
        PANDA,
        GENESIS,
        POOL_PARTY,
        RANKED,
        UNKNOWN19,
        UNKNOWN20
    }

    public enum eRannoSkins
    {
        DEFAULT,
        BLUE,
        RED,
        GREEN,
        GREY,
        PURPLE,
        SEASONAL,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        POOL_PARTY,
        CHAMPION,
        ABYSS,
        EARLY_ACCESS,
        TUXEDO,
        GOLDEN_PLUSH,
        INFAMOUS,
        RANKED,
        UNKNOWN19,
        UNKNOWN20
    }

    public enum eHodanSkins
    {
        DEFAULT,
        BLUE,
        RED,
        GREEN,
        GREY,
        PURPLE,
        SEASONAL,
        UNKNOWN7,
        CUSTOM1,
        CUSTOM2,
        UNKNOWN10,
        UNKNOWN11,
        UNKNOWN12,
        ABYSS,
        EARLY_ACCESS,
        UNKNOWN15,
        UNKNOWN16,
        UNKNOWN17,
        RANKED,
        UNKNOWN19,
        UNKNOWN20
    }
}
